### PR TITLE
GovBot Starter Template

### PR DESCRIPTION
**Pull request by iluxonchik**
As discussed on the call with @es92 today, I'm starting with the submission of the base template for the structure of the bot. It's based on the structure of https://github.com/MinaFoundation/gptSurveySummarizer, with adaptations related to bot functioning via buttons/dashboards instead of commands. From what I understood, this change is/will be approved: https://docs.google.com/document/d/1aNGYqRoUVXtOw8aef9mSQHHSIvG2thnrxMw7FCB_AhM

Please note, the code in this PR **hasn't been run/tested**. I will need to double-check with the discord.js and Discord docs relating to the channels/dashboards setup and test it out on a Discord server.

The goal of this PR is to kick-off the development process, agree on the structure, and collect the first set of practical questions, as well as dependencies and architectural decisions (note the use sqlite).

Open questions that arose during this initial setup:

1. Should the channels be created programatically or manually? Programatically is ideal, but someone with permissions will need to run them, so maybe the initial preference is to have them crated manually.
2. Where will this bot be tested? We can go with either private channels on Mina Discord or on a new server. Locally, I'll likely create a new channel to test, but we need something for the team to verify.
3. I may add an ORM. Is that okay, or are raw SQL queries preferred?
4. Related to migrations. I suggest we add them after the initial release, or at least once we have things working

Thank you.

### CODE REVIEW

**Comment by es92** [comment]
1. I think manually is fine for now, since I think its a fixed set anyway (automatically would be nice in the future if other discords end up using this too)
2. There's a server here we can use for testing https://discord.gg/2cmxYYMyHN
3. No preference from me, though I don't fully understand the tradeoffs
4. Yep migrations can wait imo

**Comment by iluxonchik** [comment]
Pushed the implementation of the SME Related functionality, tested it in a custom server, and recorded a demo of how it looks. The PR is now ready to be merged. I'll keep pushing code here in the meanwhile.

**Comment by iluxonchik** [comment]
I just noticed the PR doesn't automatically update the commits. I have been pushing them here: https://github.com/iluxonchik/mina-govbot/tree/feature/govbot-init

**Comment by CristinaEche** [comment]
PR Merged in order to have more testing capabilities, new fixes will be addressed in new PR's.

**Pull request merged**
